name: lanet_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.0.5
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Audio
  just_audio: ^0.9.35
  audio_session: ^0.1.15
  # UI
  flutter_svg: ^2.0.7
  lottie: ^2.7.0
  percent_indicator: ^4.2.3
  confetti: ^0.7.0
  flutter_animate: ^4.2.0

  # Utils
  intl: ^0.18.1
  uuid: ^4.2.2
  equatable: ^2.0.5

  # Navigation
  go_router: ^13.0.0

  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/multilingual_dataset.json
    - assets/data/level_0_fidel.csv
    - assets/animations/
    - assets/images/patterns/page_border.png
    - assets/images/illustration/
    - assets/images/categories/
    - assets/icons/
    - assets/audio/
